In [1]:
import numpy as np
import pandas as pd

In [2]:
np.__version__

'1.20.3'

In [3]:
pd.__version__

'1.3.4'

In [4]:
a = np.array([1,2,3,5,-8])

In [5]:
a.dtype

dtype('int32')

In [6]:
b = np.array((2,3,5,6,7,8))

In [7]:
L = [1,2,3,4,5,'abc']

In [8]:
type(L)

list

In [9]:
type(a)

numpy.ndarray

In [10]:
print(a)

[ 1  2  3  5 -8]


In [11]:
A = np.array([[1,2,3,4],[3,5,-7,0]])

In [12]:
A.ndim

2

In [13]:
A = np.array([[[1,2,3,4],[3,4,5,8],[9,8,7,2]],[[5,-2,-3,-4],[-3,4,-5,8],[9,8,-7,2]]])

In [14]:
A.ndim

3

In [15]:
A.shape

(2, 3, 4)

In [16]:
A.shape[0]

2

In [17]:
A.shape[1]

3

In [18]:
A.shape[2]

4

In [19]:
A

array([[[ 1,  2,  3,  4],
        [ 3,  4,  5,  8],
        [ 9,  8,  7,  2]],

       [[ 5, -2, -3, -4],
        [-3,  4, -5,  8],
        [ 9,  8, -7,  2]]])

In [20]:
A[0,1,2]

5

In [21]:
A = np.arange(10)

In [22]:
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
A = np.arange(2,100,10)

In [24]:
A

array([ 2, 12, 22, 32, 42, 52, 62, 72, 82, 92])

In [25]:
np.random.permutation(np.arange(10))

array([7, 1, 8, 0, 4, 2, 6, 9, 3, 5])

In [26]:
np.arange(100).reshape(25,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39],
       [40, 41, 42, 43],
       [44, 45, 46, 47],
       [48, 49, 50, 51],
       [52, 53, 54, 55],
       [56, 57, 58, 59],
       [60, 61, 62, 63],
       [64, 65, 66, 67],
       [68, 69, 70, 71],
       [72, 73, 74, 75],
       [76, 77, 78, 79],
       [80, 81, 82, 83],
       [84, 85, 86, 87],
       [88, 89, 90, 91],
       [92, 93, 94, 95],
       [96, 97, 98, 99]])

In [27]:
np.arange(100).reshape(25,5)

ValueError: cannot reshape array of size 100 into shape (25,5)

In [ ]:
A = np.random.permutation(np.arange(10))

In [ ]:
A

In [ ]:
A[1:5]

In [ ]:
A[1:7:2]

In [ ]:
A[::-1]

In [ ]:
A = np.arange(20).reshape(5,4)

In [ ]:
A

In [ ]:
A[2,3]

In [ ]:
A

In [ ]:
A[1:3,1:3]

In [ ]:
A[1:3,:]

In [ ]:
A[::2,:]

In [ ]:
A = np.random.permutation(np.arange(10))

In [ ]:
A

In [ ]:
A[[1,5,2]]

In [ ]:
A<5

In [ ]:
idx = A<5
A[idx]

In [ ]:
A[A<5]

In [ ]:
A[(A<5) & (A>2)]

In [ ]:
A

In [ ]:
B = A[1:5]

In [ ]:
B

In [ ]:
B[2] = -100

In [ ]:
B

In [ ]:
A

In [ ]:
B = A[1:5].copy()

In [ ]:
A

In [ ]:
B = A[A<5]

In [ ]:
B

In [ ]:
B[0] = 999

In [ ]:
B

In [ ]:
A

In [ ]:
A = np.arange(20).reshape(5,4)

In [ ]:
A

In [ ]:
A+5

In [ ]:
A.shape

In [ ]:
B = np.arange(5).reshape(5,1)

In [ ]:
B.shape

In [ ]:
A+B

In [ ]:
import pandas as pd

In [ ]:
pd.__version__

In [ ]:
A = pd.Series([2,3,5,6],index=['a','b','c','d'])

In [ ]:
type(A)

In [ ]:
A.values

In [ ]:
type(A.values)

In [ ]:

A.index

In [ ]:
type(A.index)

In [ ]:
A['a']

In [ ]:
A[0:2]

In [ ]:
A['a':'c']

In [ ]:
grads_dict = {'A':4, 'B':3.5, 'C':3, 'D':2.5}
grads = pd.Series(grads_dict)

In [ ]:
grads.values

In [ ]:
grads

In [ ]:
marks_dict = {'A':85, 'B':75, 'C':65, 'D':55}
marks = pd.Series(marks_dict)

In [ ]:
marks

In [ ]:
marks['A']

In [ ]:

marks[0:2]

In [ ]:
D = pd.DataFrame({'Marks':marks,'Grades':grads})

In [ ]:
D

In [ ]:
D.T

In [ ]:
D.values

In [ ]:
D.values[2,0]

In [ ]:
D.columns

In [ ]:
D['ScaledMarks'] = 100*(D['Marks']/90)

In [ ]:
D

In [ ]:
del D['ScaledMarks']

In [ ]:
D

In [ ]:
G = D[D['Marks']>70]

In [ ]:
G

In [ ]:
A = pd.DataFrame([{'a':1,'b':4},{'b':-3,'c':9}])

In [ ]:
A

In [ ]:
A.fillna(0)

In [ ]:
A.dropna?

In [ ]:
garades = pd.Series([4,3.5,3,2.5],index = ['A','A-','B','C'])
marks = pd.Series([85,75,65,55],index = ['A','A-','B','C'])
sheet = pd.DataFrame({'Gr':garades,'Mr':marks})

In [ ]:
sheet

In [ ]:
sheet['Gr']

In [ ]:
sheet.columns

In [ ]:
sheet.values

In [ ]:
sheet.index

In [ ]:
sheet['NewC'] = np.random.randint(1,10,4)

In [ ]:
sheet

In [ ]:
sheet.rename(columns={'NewC':'ColC'})

In [ ]:
sheet[sheet['Mr']>70]

In [ ]:
data = pd.Series(['a','b','c'],index=[1,3,5])

In [ ]:
data[1]

In [ ]:
data[1:3]

In [ ]:
data.loc[1:3]

In [ ]:
data.iloc[1:3]

In [ ]:
D

In [ ]:
D.iloc[2,:]

In [ ]:
D.iloc[::-1,:]

In [ ]:
A = pd.DataFrame([{'a':1,'b':2},{'b':3,'c':4}])

In [ ]:
A

In [ ]:
A.dropna()

In [ ]:
A = pd.DataFrame([{'a':1,'b':2},{'b':3,'c':4}])

In [ ]:
A.fillna(0)

In [ ]:
A = pd.DataFrame([{'a':1,'b':2},{'b':3,'c':4}])

In [ ]:
A.isnull()

In [ ]:
A['c'].isnull()

In [ ]:
df = pd.DataFrame(np.random.randint(0,10,(3,4)),columns=list('ABCD'))

In [ ]:
df

In [ ]:
df2 = np.sin(df*np.pi/4)

In [ ]:
type(df2)

In [ ]:
A = pd.DataFrame(np.random.randint(0,20,(2,2)),columns=list('AB'))
B = pd.DataFrame(np.random.randint(0,30,(3,3)),columns=list('BAC'))

In [ ]:
A

In [ ]:
B

In [ ]:
A+B

In [ ]:
(A+B).fillna(0)

In [ ]:
A.add(B,fill_value=0)

In [ ]:
df = pd.DataFrame({'key':list('ABCABC'),'val':np.arange(6)},columns=['key','val'])

In [ ]:
df

In [ ]:
df.groupby('key').sum()

In [ ]:
df = pd.read_csv(r'C:\Users\User\Desktop\python\adult.data',header=None)

In [ ]:
df.shape

In [ ]:
df.columns

In [ ]:
df.columns = ['C'+str(x) for x in range(df.shape[1])]

In [ ]:
df.columns

In [ ]:
df['C14']

In [ ]:
df.loc[:,'C0']

In [ ]:
df.loc[:,['C0','C14']]

In [ ]:
df.head()

In [ ]:
df.tail()

In [ ]:
df['C14'].unique()

In [ ]:
L = df['C14'].unique()

In [ ]:
L[0]

In [ ]:
L[1]

In [ ]:
idx = df['C14']==L[0]

In [ ]:
idx

In [ ]:
df['C14'].loc[idx] = -1

In [ ]:
df['C14'].loc[~idx] = 1

In [ ]:
df['C14']

In [ ]:
df['C14'].unique()

In [ ]:
df.head()

In [ ]:
df['C1'].unique().size

In [ ]:
df = pd.get_dummies(df,columns=['C1'])

In [ ]:
df.shape

In [ ]:
df.columns

In [ ]:
15-1+9

In [ ]:
df = pd.read_csv(r'C:\Users\User\Desktop\python\adult.data',header=None)

In [ ]:
df.columns = ['C'+str(x) for x in range(df.shape[1])]

In [ ]:
df['C1'].isnull().sum()

In [ ]:
df['C1'].unique()

In [ ]:
df2 = pd.get_dummies(df,columns=['C1','C14'])

In [ ]:
df2.columns

In [ ]:
df.isnull().sum()

In [ ]:
df.info()

In [ ]:
df2.head()

In [ ]:
df2.to_csv(r"C:\Sales\abc.csv")