In [1]:
import numpy as np

# The Basics

In [2]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [3]:
a = np.array(([6,5], [6,5]))
print(a)

[[6 5]
 [6 5]]


In [4]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])

In [5]:
b

array([[9., 8., 7.],
       [6., 5., 4.]])

In [6]:
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [7]:
# get dimension
a.ndim

2

In [8]:
# get shape
b.shape

(2, 3)

In [9]:
# get size
a.itemsize

4

In [10]:
# get total size
a.size

4

In [11]:
# get total size
a.nbytes

16

# Accessing/Changing specific elements, rows, columns, etc

In [12]:
a = np.array([[1,2,3,4,5,6,7,],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [13]:
a.shape

(2, 7)

In [14]:
# get a specific element [r, c]
a[0,5]

6

In [15]:
a[1,5]

13

In [16]:
a[1,-1]

14

In [17]:
a[1,-2]

13

In [18]:
# get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [19]:
# get a specific column
a[:, 2]

array([ 3, 10])

In [20]:
# get a little more fancy [startindex:endindex:stepsize]
a[0, 1:6:2]

array([2, 4, 6])

In [21]:
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [22]:
a[:, 2] = 5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [23]:
# 3-d example
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [24]:
# get specific element (work outside in)
b[1,1,0]

7

In [25]:
b[0,1,1]

4

In [26]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [27]:
b[:,0,:]

array([[1, 2],
       [5, 6]])

In [28]:
b[:,0,0]

array([1, 5])

In [29]:
# replace
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [30]:
b[:,1,:] = [[9,9],[8,8]]

In [31]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

# Initializing Different Type of Arrays

In [32]:
# all 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [33]:
# all 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [34]:
# any other number 
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [35]:
# any other number (full_like)
np.full_like(a.shape, 4)

array([4, 4])

In [36]:
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [37]:
# Random decimal number
np.random.rand(4,2)

array([[0.43685139, 0.85859222],
       [0.15255823, 0.17225146],
       [0.52488865, 0.80560363],
       [0.62765597, 0.930721  ]])

In [38]:
np.random.rand(4,2,3)

array([[[0.10737109, 0.77829419, 0.31896865],
        [0.55694955, 0.5728432 , 0.40019943]],

       [[0.93529669, 0.00418937, 0.64974617],
        [0.72821244, 0.31434282, 0.29879304]],

       [[0.75089986, 0.74033064, 0.32785129],
        [0.83372808, 0.88040309, 0.90548214]],

       [[0.97941642, 0.41391024, 0.22345176],
        [0.42638895, 0.9293054 , 0.99456842]]])

In [39]:
np.random.random_sample(a.shape)

array([[0.09198044, 0.29704614, 0.34207823, 0.04606637, 0.45494864,
        0.57757547, 0.62317732],
       [0.50995419, 0.16316871, 0.17961638, 0.30538178, 0.71923568,
        0.69282552, 0.38558464]])

In [40]:
# Random integer values
np.random.randint(7, size=(3,3))

array([[0, 3, 2],
       [4, 3, 1],
       [4, 0, 0]])

In [41]:
np.random.randint(4,7, size=(3,3))

array([[5, 4, 6],
       [4, 5, 4],
       [5, 5, 6]])

In [42]:
np.random.randint(-4,7, size=(3,3))

array([[-2,  6,  5],
       [ 0,  4,  1],
       [-4,  1, -1]])

In [43]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [44]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [45]:
arr = np.array([1,2,3])
r1 = np.repeat(arr,3)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [46]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [47]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:4,1:4] = z

print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [48]:
a = np.array([1,2,3])
b = a
b

array([1, 2, 3])

In [49]:
a = np.array([1,2,3])
b = a
b[0] = 100
print(b)

[100   2   3]


In [50]:
print(a)

[100   2   3]


In [51]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(b)

[100   2   3]


In [52]:
print(a)

[1 2 3]


# Mathematics

In [53]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [54]:
a+2

array([3, 4, 5, 6])

In [55]:
a - 2

array([-1,  0,  1,  2])

In [56]:
a * 2

array([2, 4, 6, 8])

In [57]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [58]:
a += 2

In [59]:
print(a)

[3 4 5 6]


In [60]:
b = np.array([1,0,1,0])
a + b

array([4, 4, 6, 6])

In [61]:
a**2

array([ 9, 16, 25, 36], dtype=int32)

In [62]:
# take the sin
np.sin(a)

array([ 0.14112001, -0.7568025 , -0.95892427, -0.2794155 ])

In [63]:
np.cos(a)

array([-0.9899925 , -0.65364362,  0.28366219,  0.96017029])

# linear algebra

In [64]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)

print(b)
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [65]:
# find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

# Statistics

In [66]:
stats = np.array([[1,2,3,],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [67]:
np.min(stats)

1

In [68]:
np.max(stats)

6

In [69]:
np.min(stats, axis=1)

array([1, 4])

In [70]:
np.min(stats, axis=0)

array([1, 2, 3])

In [71]:
np.max(stats, axis=0)

array([4, 5, 6])

In [72]:
np.max(stats, axis=1)

array([3, 6])

In [73]:
np.sum(stats, axis=0)

array([5, 7, 9])

# Reorganizing Array

In [74]:
before = np.array([[1,2,3,4],[5,6,7,8]])

print(before)
                  

[[1 2 3 4]
 [5 6 7 8]]


In [75]:
before = np.array([[1,2,3,4],[5,6,7,8]])

print(before)

after = before.reshape((4,2))
print(after)
            

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [76]:
before = np.array([[1,2,3,4],[5,6,7,8]])

print(before)

after = before.reshape((2,2,2))
print(after)
           

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [77]:
before = np.array([[1,2,3,4],[5,6,7,8]])

print(before)

after = before.reshape((3,2))
print(after)
           

[[1 2 3 4]
 [5 6 7 8]]


ValueError: cannot reshape array of size 8 into shape (3,2)

In [78]:
before.shape

(2, 4)

In [79]:
import numpy as np

In [80]:
# vertically stacking vectors

v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8]) 

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [81]:
# Horizontal stack

h1 = np.ones((2,4))
h2 = np.zeros((2,2))

In [82]:
h2

array([[0., 0.],
       [0., 0.]])

In [83]:
np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

# Miscellaneous

# Load Data from file

In [84]:
datas = np.genfromtxt('C:/Sales/datas.txt', delimiter=',')

In [85]:
datas

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

In [86]:
datas.astype('int32')

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

In [87]:
datas

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

In [88]:
datas = datas.astype('int32')
print(datas)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


# Boolean Masking and Advanced Indexing

In [89]:
datas > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [90]:
datas < 5

array([[ True, False, False, False, False, False,  True,  True, False,
        False, False, False,  True,  True,  True,  True,  True, False],
       [ True, False, False, False, False, False,  True, False, False,
         True,  True,  True, False, False, False,  True, False, False],
       [ True, False, False, False, False, False,  True,  True, False,
         True,  True,  True, False, False, False,  True, False, False]])

In [91]:
datas == 50

array([[False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False]])

In [92]:
datas[datas > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [93]:
datas[datas < 50]

array([ 1, 13, 21, 11,  4,  3, 34,  6,  7,  8,  0,  1,  2,  3,  4,  5,  3,
       42, 12, 33,  4,  6,  4,  3,  4,  5,  6,  7,  0, 11, 12,  1, 22, 33,
       11, 11,  2,  1,  0,  1,  2,  9,  8,  7,  1])

In [94]:
datas[datas == 50]

array([], dtype=int32)

In [95]:
datas[datas != 50]

array([  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
         1,   2,   3,   4,   5,   3,  42,  12,  33, 766,  75,   4,  55,
         6,   4,   3,   4,   5,   6,   7,   0,  11,  12,   1,  22,  33,
        11, 999,  11,   2,   1,  78,   0,   1,   2,   9,   8,   7,   1,
        76,  88])

In [96]:
datas[datas <= 50]

array([ 1, 13, 21, 11,  4,  3, 34,  6,  7,  8,  0,  1,  2,  3,  4,  5,  3,
       42, 12, 33,  4,  6,  4,  3,  4,  5,  6,  7,  0, 11, 12,  1, 22, 33,
       11, 11,  2,  1,  0,  1,  2,  9,  8,  7,  1])

In [97]:
datas[datas >= 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [98]:
# you can index with a list in numpy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [99]:
np.any(datas > 50, axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [100]:
np.all(datas > 50, axis=0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [101]:
np.any(datas > 50, axis=1)

array([ True,  True,  True])

In [102]:
((datas > 50) & (datas < 100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [103]:
(~(datas > 50) & (datas < 100))

array([[ True,  True,  True,  True, False, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

In [104]:
c = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30]])

In [105]:
c

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [106]:
c.shape

(6, 5)

In [108]:
c[2,3]

14

In [111]:
c[2, :]

array([11, 12, 13, 14, 15])

In [112]:
c[:, 2]

array([ 3,  8, 13, 18, 23, 28])

In [113]:
c[2:4, 0:2]

array([[11, 12],
       [16, 17]])

In [114]:
c[2:4]

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [115]:
c[0:2]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [116]:
c[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])

In [117]:
c[[0,4,5], 3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])